package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"

	"github.com/overmindv/api-gateway/internal/client/entities"
	"github.com/overmindv/api-gateway/internal/client/users"
	"github.com/overmindv/api-gateway/internal/graphql/generated"
	"github.com/overmindv/api-gateway/internal/graphql/model"
	"github.com/overmindv/api-gateway/internal/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	response, err := r.Users.Register(ctx, users.RegisterInput{
		Email: input.Email, Password: input.Password, Username: input.Username,
		FirstName: stringValue(input.FirstName), LastName: stringValue(input.LastName), BirthDate: input.BirthDate, Phone: stringValue(input.Phone),
	})
	if err != nil {
		return nil, err
	}
	if response == nil || response.User == nil {
		return nil, errors.New("users returned an empty registration response")
	}

	result := toAuthPayload(response)
	result.User = r.hydrateUsers(ctx, []*users.User{response.User})[0]

	return result, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	response, err := r.Users.Login(ctx, users.LoginInput{Email: input.Email, Password: input.Password})
	if err != nil {
		return nil, err
	}
	if response == nil || response.User == nil {
		return nil, errors.New("users returned an empty login response")
	}

	result := toAuthPayload(response)
	result.User = r.hydrateUsers(ctx, []*users.User{response.User})[0]

	return result, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	if _, err := middleware.RequireAuth(ctx); err != nil {
		return nil, err
	}
	response, err := r.Users.UpdateUser(ctx, id, users.UpdateUserInput{
		Username: input.Username, FirstName: input.FirstName, LastName: input.LastName,
		BirthDate: input.BirthDate, ClearBirthDate: boolValue(input.ClearBirthDate), Phone: input.Phone,
	})
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("users returned an empty update response")
	}

	return r.hydrateUsers(ctx, []*users.User{response})[0], nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	if _, err := middleware.RequireAuth(ctx); err != nil {
		return false, err
	}
	response, err := r.Users.DeleteUser(ctx, id)
	if err != nil {
		return false, err
	}

	return response, nil
}

// SetUserAdmin is the resolver for the setUserAdmin field.
func (r *mutationResolver) SetUserAdmin(ctx context.Context, id string, admin bool) (*model.User, error) {
	if _, err := middleware.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	response, err := r.Users.SetUserAdmin(ctx, id, admin)
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("users returned an empty admin response")
	}

	return r.hydrateUsers(ctx, []*users.User{response})[0], nil
}

// SetUserAdminByUsername is the resolver for the setUserAdminByUsername field.
func (r *mutationResolver) SetUserAdminByUsername(ctx context.Context, username string, admin bool) (*model.User, error) {
	if _, err := middleware.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	response, err := r.Users.SetUserAdminByUsername(ctx, username, admin)
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("users returned an empty admin response")
	}

	return r.hydrateUsers(ctx, []*users.User{response})[0], nil
}

// CreateUniversity is the resolver for the createUniversity field.
func (r *mutationResolver) CreateUniversity(ctx context.Context, input model.CreateUniversityInput) (*model.University, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.CreateUniversity(ctx, entities.University{Name: input.Name, ShortName: stringValue(input.ShortName), City: stringValue(input.City), Country: stringValue(input.Country), WebsiteURL: stringValue(input.WebsiteURL), LogoFileID: input.LogoFileID, Status: statusValue(input.Status)}, actor)
	if err != nil {
		return nil, err
	}

	return universityModel(result), nil
}

// UpdateUniversity is the resolver for the updateUniversity field.
func (r *mutationResolver) UpdateUniversity(ctx context.Context, id string, input model.UpdateUniversityInput) (*model.University, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.UpdateUniversity(ctx, id, entities.University{Name: input.Name, ShortName: stringValue(input.ShortName), City: stringValue(input.City), Country: stringValue(input.Country), WebsiteURL: stringValue(input.WebsiteURL), LogoFileID: input.LogoFileID}, actor)
	if err != nil {
		return nil, err
	}

	return universityModel(result), nil
}

// DeleteUniversity is the resolver for the deleteUniversity field.
func (r *mutationResolver) DeleteUniversity(ctx context.Context, id string) (bool, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return false, err
	}
	err = r.Catalog.DeleteUniversity(ctx, id, actor)

	return err == nil, err
}

// ChangeUniversityStatus is the resolver for the changeUniversityStatus field.
func (r *mutationResolver) ChangeUniversityStatus(ctx context.Context, id string, status model.CatalogStatus) (*model.University, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.ChangeUniversityStatus(ctx, id, status.String(), actor)
	if err != nil {
		return nil, err
	}

	return universityModel(result), nil
}

// CreateProgram is the resolver for the createProgram field.
func (r *mutationResolver) CreateProgram(ctx context.Context, input model.CreateProgramInput) (*model.Program, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.CreateProgram(ctx, entities.Program{UniversityID: input.UniversityID, Name: input.Name, ShortName: stringValue(input.ShortName), Faculty: stringValue(input.Faculty), DegreeLevel: degreeValue(input.DegreeLevel), StartYear: input.StartYear, Status: statusValue(input.Status)}, actor)
	if err != nil {
		return nil, err
	}

	return programModel(result), nil
}

// UpdateProgram is the resolver for the updateProgram field.
func (r *mutationResolver) UpdateProgram(ctx context.Context, id string, input model.UpdateProgramInput) (*model.Program, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	universityID := input.UniversityID
	if boolValue(input.ClearUniversity) {
		universityID = nil
	} else if universityID == nil {
		current, err := r.Catalog.GetProgram(ctx, id)
		if err != nil {
			return nil, err
		}
		universityID = current.UniversityID
	}
	result, err := r.Catalog.UpdateProgram(ctx, id, entities.Program{UniversityID: universityID, Name: input.Name, ShortName: stringValue(input.ShortName), Faculty: stringValue(input.Faculty), DegreeLevel: degreeValue(input.DegreeLevel), StartYear: input.StartYear}, actor)
	if err != nil {
		return nil, err
	}

	return programModel(result), nil
}

// DeleteProgram is the resolver for the deleteProgram field.
func (r *mutationResolver) DeleteProgram(ctx context.Context, id string) (bool, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return false, err
	}
	err = r.Catalog.DeleteProgram(ctx, id, actor)

	return err == nil, err
}

// ChangeProgramStatus is the resolver for the changeProgramStatus field.
func (r *mutationResolver) ChangeProgramStatus(ctx context.Context, id string, status model.CatalogStatus) (*model.Program, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.ChangeProgramStatus(ctx, id, status.String(), actor)
	if err != nil {
		return nil, err
	}

	return programModel(result), nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.CreateCourseInput) (*model.Course, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.CreateCourse(ctx, entities.Course{ProgramID: input.ProgramID, Name: input.Name, Slug: stringValue(input.Slug), Description: stringValue(input.Description), Semester: input.Semester, YearNumber: input.YearNumber, Status: statusValue(input.Status)}, actor)
	if err != nil {
		return nil, err
	}

	return courseModel(result), nil
}

// UpdateCourse is the resolver for the updateCourse field.
func (r *mutationResolver) UpdateCourse(ctx context.Context, id string, input model.UpdateCourseInput) (*model.Course, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	programID := input.ProgramID
	if boolValue(input.ClearProgram) {
		programID = nil
	} else if programID == nil {
		current, err := r.Catalog.GetCourse(ctx, id)
		if err != nil {
			return nil, err
		}
		programID = current.ProgramID
	}
	result, err := r.Catalog.UpdateCourse(ctx, id, entities.Course{ProgramID: programID, Name: input.Name, Slug: stringValue(input.Slug), Description: stringValue(input.Description), Semester: input.Semester, YearNumber: input.YearNumber}, actor)
	if err != nil {
		return nil, err
	}

	return courseModel(result), nil
}

// DeleteCourse is the resolver for the deleteCourse field.
func (r *mutationResolver) DeleteCourse(ctx context.Context, id string) (bool, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return false, err
	}
	err = r.Catalog.DeleteCourse(ctx, id, actor)

	return err == nil, err
}

// ChangeCourseStatus is the resolver for the changeCourseStatus field.
func (r *mutationResolver) ChangeCourseStatus(ctx context.Context, id string, status model.CatalogStatus) (*model.Course, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.ChangeCourseStatus(ctx, id, status.String(), actor)
	if err != nil {
		return nil, err
	}

	return courseModel(result), nil
}

// CreateTopic is the resolver for the createTopic field.
func (r *mutationResolver) CreateTopic(ctx context.Context, input model.CreateTopicInput) (*model.Topic, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.CreateTopic(ctx, entities.Topic{CourseID: input.CourseID, ParentTopicID: input.ParentTopicID, Title: input.Title, Slug: stringValue(input.Slug), Description: stringValue(input.Description), OrderIndex: intValue(input.OrderIndex, 0), Difficulty: difficultyValue(input.Difficulty), Status: statusValue(input.Status)}, actor)
	if err != nil {
		return nil, err
	}

	return topicModel(result), nil
}

// UpdateTopic is the resolver for the updateTopic field.
func (r *mutationResolver) UpdateTopic(ctx context.Context, id string, input model.UpdateTopicInput) (*model.Topic, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	courseID := input.CourseID
	parentID := input.ParentTopicID
	needsCurrent := (!boolValue(input.ClearCourse) && courseID == nil) || (parentID == nil && !boolValue(input.ClearParentTopic))
	var current entities.Topic
	if needsCurrent {
		current, err = r.Catalog.GetTopic(ctx, id)
		if err != nil {
			return nil, err
		}
	}
	if boolValue(input.ClearCourse) {
		courseID = nil
	} else if courseID == nil {
		courseID = current.CourseID
	}
	if boolValue(input.ClearParentTopic) {
		parentID = nil
	} else if parentID == nil {
		parentID = current.ParentTopicID
	}
	result, err := r.Catalog.UpdateTopic(ctx, id, entities.Topic{CourseID: courseID, ParentTopicID: parentID, Title: input.Title, Slug: stringValue(input.Slug), Description: stringValue(input.Description), OrderIndex: intValue(input.OrderIndex, 0), Difficulty: difficultyValue(input.Difficulty)}, actor)
	if err != nil {
		return nil, err
	}

	return topicModel(result), nil
}

// DeleteTopic is the resolver for the deleteTopic field.
func (r *mutationResolver) DeleteTopic(ctx context.Context, id string) (bool, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return false, err
	}
	err = r.Catalog.DeleteTopic(ctx, id, actor)

	return err == nil, err
}

// ChangeTopicStatus is the resolver for the changeTopicStatus field.
func (r *mutationResolver) ChangeTopicStatus(ctx context.Context, id string, status model.CatalogStatus) (*model.Topic, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.ChangeTopicStatus(ctx, id, status.String(), actor)
	if err != nil {
		return nil, err
	}

	return topicModel(result), nil
}

// AddTopicPrerequisite is the resolver for the addTopicPrerequisite field.
func (r *mutationResolver) AddTopicPrerequisite(ctx context.Context, input model.TopicPrerequisiteInput) (*model.TopicPrerequisite, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.Catalog.AddPrerequisite(ctx, input.TopicID, input.PrerequisiteTopicID, actor)
	if err != nil {
		return nil, err
	}

	return prerequisiteModel(result), nil
}

// RemoveTopicPrerequisite is the resolver for the removeTopicPrerequisite field.
func (r *mutationResolver) RemoveTopicPrerequisite(ctx context.Context, input model.TopicPrerequisiteInput) (bool, error) {
	actor, err := adminActor(ctx)
	if err != nil {
		return false, err
	}
	err = r.Catalog.RemovePrerequisite(ctx, input.TopicID, input.PrerequisiteTopicID, actor)

	return err == nil, err
}

// CreateITTask is the resolver for the createITTask field.
func (r *mutationResolver) CreateITTask(ctx context.Context, input model.ITTaskInput) (*model.ITTask, error) {
	actor, err := tasksActor(ctx, true)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.Create(ctx, tasksInput(input), actor)
	if err != nil {
		return nil, err
	}

	return taskModel(result), nil
}

// UpdateITTask is the resolver for the updateITTask field.
func (r *mutationResolver) UpdateITTask(ctx context.Context, id string, input model.ITTaskInput) (*model.ITTask, error) {
	actor, err := tasksActor(ctx, true)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.Update(ctx, id, tasksInput(input), actor)
	if err != nil {
		return nil, err
	}

	return taskModel(result), nil
}

// ChangeITTaskStatus is the resolver for the changeITTaskStatus field.
func (r *mutationResolver) ChangeITTaskStatus(ctx context.Context, id string, status model.ITTaskStatus) (*model.ITTask, error) {
	actor, err := tasksActor(ctx, true)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.ChangeStatus(ctx, id, status.String(), actor)
	if err != nil {
		return nil, err
	}

	return taskModel(result), nil
}

// DeleteITTask is the resolver for the deleteITTask field.
func (r *mutationResolver) DeleteITTask(ctx context.Context, id string) (bool, error) {
	actor, err := tasksActor(ctx, true)
	if err != nil {
		return false, err
	}
	if err := r.Tasks.Delete(ctx, id, actor); err != nil {
		return false, err
	}

	return true, nil
}

// SubmitITTaskAnswer is the resolver for the submitITTaskAnswer field.
func (r *mutationResolver) SubmitITTaskAnswer(ctx context.Context, taskID string, input model.ITSubmissionInput) (*model.ITSubmission, error) {
	actor, err := tasksActor(ctx, false)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.Submit(ctx, taskID, submissionInput(input), actor)
	if err != nil {
		return nil, err
	}

	return submissionModel(result), nil
}

// SubmitITTaskCode is the resolver for the submitITTaskCode field.
func (r *mutationResolver) SubmitITTaskCode(ctx context.Context, taskID string, input model.ITCodeSubmissionInput) (*model.ITCodeSubmission, error) {
	actor, err := tasksActor(ctx, false)
	if err != nil {
		return nil, err
	}

	result, err := r.Tasks.SubmitCode(ctx, taskID, codeSubmissionInput(input), actor)
	if err != nil {
		return nil, err
	}

	return codeSubmissionModel(result), nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	actor, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if actor.UserID != id {
		if _, err := middleware.RequireAdmin(ctx); err != nil {
			return nil, err
		}
	}
	response, err := r.Resolver.Users.GetUser(ctx, id) //nolint:staticcheck // Поле Users конфликтует с GraphQL resolver Users.
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("users returned an empty get response")
	}

	return r.hydrateUsers(ctx, []*users.User{response})[0], nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	if _, err := middleware.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	response, err := r.Resolver.Users.GetUserByUsername(ctx, username) //nolint:staticcheck // Поле Users конфликтует с GraphQL resolver Users.
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("users returned an empty get response")
	}

	return r.hydrateUsers(ctx, []*users.User{response})[0], nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, search *string, limit *int, offset *int) ([]*model.User, error) {
	if _, err := middleware.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	response, err := r.Resolver.Users.ListUsers(ctx, stringValue(search), intValue(limit, 20), intValue(offset, 0)) //nolint:staticcheck // Поле Users конфликтует с GraphQL resolver Users.
	if err != nil {
		return nil, err
	}
	return r.hydrateUsers(ctx, response), nil
}

// Universities is the resolver for the universities field.
func (r *queryResolver) Universities(ctx context.Context, filter *model.CatalogFilter, pagination *model.PaginationInput) ([]*model.University, error) {
	result, err := r.Catalog.ListUniversities(ctx, catalogOptions(filter, pagination))
	if err != nil {
		return nil, err
	}
	output := make([]*model.University, 0, len(result))
	for _, item := range result {
		output = append(output, universityModel(item))
	}

	return output, nil
}

// University is the resolver for the university field.
func (r *queryResolver) University(ctx context.Context, id string) (*model.University, error) {
	result, err := r.Catalog.GetUniversity(ctx, id)
	if err != nil {
		return nil, err
	}

	return universityModel(result), nil
}

// Programs is the resolver for the programs field.
func (r *queryResolver) Programs(ctx context.Context, universityID *string, filter *model.CatalogFilter, pagination *model.PaginationInput) ([]*model.Program, error) {
	result, err := r.Catalog.ListPrograms(ctx, stringValue(universityID), catalogOptions(filter, pagination))
	if err != nil {
		return nil, err
	}
	output := make([]*model.Program, 0, len(result))
	for _, item := range result {
		output = append(output, programModel(item))
	}

	return output, nil
}

// Program is the resolver for the program field.
func (r *queryResolver) Program(ctx context.Context, id string) (*model.Program, error) {
	result, err := r.Catalog.GetProgram(ctx, id)
	if err != nil {
		return nil, err
	}

	return programModel(result), nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context, programID *string, filter *model.CatalogFilter, pagination *model.PaginationInput) ([]*model.Course, error) {
	result, err := r.Catalog.ListCourses(ctx, stringValue(programID), catalogOptions(filter, pagination))
	if err != nil {
		return nil, err
	}
	output := make([]*model.Course, 0, len(result))
	for _, item := range result {
		output = append(output, courseModel(item))
	}

	return output, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	result, err := r.Catalog.GetCourse(ctx, id)
	if err != nil {
		return nil, err
	}

	return courseModel(result), nil
}

// Topics is the resolver for the topics field.
func (r *queryResolver) Topics(ctx context.Context, courseID *string, filter *model.CatalogFilter, pagination *model.PaginationInput) ([]*model.Topic, error) {
	result, err := r.Catalog.ListTopics(ctx, stringValue(courseID), catalogOptions(filter, pagination))
	if err != nil {
		return nil, err
	}
	output := make([]*model.Topic, 0, len(result))
	for _, item := range result {
		output = append(output, topicModel(item))
	}

	return output, nil
}

// Topic is the resolver for the topic field.
func (r *queryResolver) Topic(ctx context.Context, id string) (*model.Topic, error) {
	result, err := r.Catalog.GetTopic(ctx, id)
	if err != nil {
		return nil, err
	}

	return topicModel(result), nil
}

// TopicTree is the resolver for the topicTree field.
func (r *queryResolver) TopicTree(ctx context.Context, courseID *string) ([]*model.TopicTreeNode, error) {
	result, err := r.Catalog.TopicTree(ctx, stringValue(courseID))
	if err != nil {
		return nil, err
	}
	output := make([]*model.TopicTreeNode, 0, len(result))
	for _, item := range result {
		output = append(output, treeModel(item))
	}

	return output, nil
}

// TopicPrerequisites is the resolver for the topicPrerequisites field.
func (r *queryResolver) TopicPrerequisites(ctx context.Context, topicID string) ([]*model.TopicPrerequisite, error) {
	result, err := r.Catalog.ListPrerequisites(ctx, topicID)
	if err != nil {
		return nil, err
	}
	output := make([]*model.TopicPrerequisite, 0, len(result))
	for _, item := range result {
		output = append(output, prerequisiteModel(item))
	}

	return output, nil
}

// ValidateCatalogBinding is the resolver for the validateCatalogBinding field.
func (r *queryResolver) ValidateCatalogBinding(ctx context.Context, input model.CatalogBindingInput) (*model.CatalogValidationResult, error) {
	result, err := r.Catalog.ValidateBinding(ctx, entities.Binding{UniversityID: input.UniversityID, ProgramID: input.ProgramID, CourseID: input.CourseID, TopicID: input.TopicID})
	if err != nil {
		return nil, err
	}

	return &model.CatalogValidationResult{Valid: result.Valid}, nil
}

// ItTasks is the resolver for the itTasks field.
func (r *queryResolver) ItTasks(ctx context.Context, filter *model.ITTaskFilter, pagination *model.PaginationInput) (*model.ITTaskList, error) {
	result, err := r.Tasks.ListPublished(ctx, publicTaskFilter(filter, pagination))
	if err != nil {
		return nil, err
	}

	return taskListModel(result), nil
}

// ItTask is the resolver for the itTask field.
func (r *queryResolver) ItTask(ctx context.Context, id string) (*model.ITTask, error) {
	result, err := r.Tasks.GetPublished(ctx, id)
	if err != nil {
		return nil, err
	}

	return publicTaskModel(result), nil
}

// AdminITTasks is the resolver for the adminITTasks field.
func (r *queryResolver) AdminITTasks(ctx context.Context, filter *model.ITAdminTaskFilter, pagination *model.PaginationInput) (*model.ITTaskList, error) {
	actor, err := tasksActor(ctx, true)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.ListAdmin(ctx, adminTaskFilter(filter, pagination), actor)
	if err != nil {
		return nil, err
	}

	return taskListModel(result), nil
}

// AdminITTask is the resolver for the adminITTask field.
func (r *queryResolver) AdminITTask(ctx context.Context, id string) (*model.ITTask, error) {
	actor, err := tasksActor(ctx, true)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.GetAdmin(ctx, id, actor)
	if err != nil {
		return nil, err
	}

	return taskModel(result), nil
}

// ItSubmission is the resolver for the itSubmission field.
func (r *queryResolver) ItSubmission(ctx context.Context, id string) (*model.ITSubmission, error) {
	actor, err := tasksActor(ctx, false)
	if err != nil {
		return nil, err
	}
	result, err := r.Tasks.GetSubmission(ctx, id, actor)
	if err != nil {
		return nil, err
	}

	return submissionModel(result), nil
}

// MyITSubmissions is the resolver for the myITSubmissions field.
func (r *queryResolver) MyITSubmissions(ctx context.Context, taskID *string, pagination *model.PaginationInput) (*model.ITSubmissionList, error) {
	actor, err := tasksActor(ctx, false)
	if err != nil {
		return nil, err
	}
	limit, offset := 50, 0
	if pagination != nil {
		limit = intValue(pagination.Limit, 50)
		offset = intValue(pagination.Offset, 0)
	}
	result, err := r.Tasks.ListMySubmissions(ctx, taskID, limit, offset, actor)
	if err != nil {
		return nil, err
	}

	return submissionListModel(result), nil
}

// ItCodeSubmission is the resolver for the itCodeSubmission field.
func (r *queryResolver) ItCodeSubmission(ctx context.Context, id string) (*model.ITCodeSubmission, error) {
	actor, err := tasksActor(ctx, false)
	if err != nil {
		return nil, err
	}

	result, err := r.Tasks.GetCodeSubmission(ctx, id, actor)
	if err != nil {
		return nil, err
	}

	return codeSubmissionModel(result), nil
}

// MyITCodeSubmissions is the resolver for the myITCodeSubmissions field.
func (r *queryResolver) MyITCodeSubmissions(ctx context.Context, taskID *string, pagination *model.PaginationInput) (*model.ITCodeSubmissionList, error) {
	actor, err := tasksActor(ctx, false)
	if err != nil {
		return nil, err
	}

	limit, offset := 50, 0
	if pagination != nil {
		limit = intValue(pagination.Limit, 50)
		offset = intValue(pagination.Offset, 0)
	}

	result, err := r.Tasks.ListMyCodeSubmissions(ctx, taskID, limit, offset, actor)
	if err != nil {
		return nil, err
	}

	return codeSubmissionListModel(result), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
