package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"

	"github.com/overmindv/laserbeak/internal/client/arcee"
	"github.com/overmindv/laserbeak/internal/graphql/generated"
	"github.com/overmindv/laserbeak/internal/graphql/model"
	"github.com/overmindv/laserbeak/internal/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	response, err := r.Users.Register(ctx, arcee.RegisterInput{
		Email: input.Email, Password: input.Password, Username: input.Username,
		FirstName: stringValue(input.FirstName), LastName: stringValue(input.LastName), BirthDate: input.BirthDate, Phone: stringValue(input.Phone),
	})
	if err != nil {
		return nil, err
	}
	if response == nil || response.User == nil {
		return nil, errors.New("arcee returned an empty registration response")
	}

	return toAuthPayload(response), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	response, err := r.Users.Login(ctx, arcee.LoginInput{Email: input.Email, Password: input.Password})
	if err != nil {
		return nil, err
	}
	if response == nil || response.User == nil {
		return nil, errors.New("arcee returned an empty login response")
	}

	return toAuthPayload(response), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	if _, err := middleware.RequireAuth(ctx); err != nil {
		return nil, err
	}
	response, err := r.Users.UpdateUser(ctx, id, arcee.UpdateUserInput{
		Username: input.Username, FirstName: input.FirstName, LastName: input.LastName,
		BirthDate: input.BirthDate, ClearBirthDate: boolValue(input.ClearBirthDate), Phone: input.Phone,
	})
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("arcee returned an empty update response")
	}

	return toUser(response), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	if _, err := middleware.RequireAuth(ctx); err != nil {
		return false, err
	}
	response, err := r.Users.DeleteUser(ctx, id)
	if err != nil {
		return false, err
	}

	return response, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	if _, err := middleware.RequireAuth(ctx); err != nil {
		return nil, err
	}
	response, err := r.Resolver.Users.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}
	if response == nil {
		return nil, errors.New("arcee returned an empty get response")
	}

	return toUser(response), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*model.User, error) {
	if _, err := middleware.RequireAuth(ctx); err != nil {
		return nil, err
	}
	response, err := r.Resolver.Users.ListUsers(ctx, intValue(limit, 20), intValue(offset, 0))
	if err != nil {
		return nil, err
	}
	users := make([]*model.User, 0, len(response))
	for _, user := range response {
		if user != nil {
			users = append(users, toUser(user))
		}
	}

	return users, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
